max_width = 100
hard_tabs = false
tab_spaces = 4
edition = "2021"
use_small_heuristics = "Max"
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
format_code_in_doc_comments = true
normalize_doc_attributes = true
wrap_comments = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
format_macro_matchers = true
format_macro_bodies = true
empty_item_single_line = false
force_explicit_abi = true
format_strings = true
remove_nested_parens = true
use_field_init_shorthand = true