debug = true
# 指定测试环境配置
profile = "test"
[tracing]
log_level = "info"

[server]
host = "0.0.0.0"
port = 3000

[database]
username = "postgres"
password = "postgres"
host = "127.0.0.1"
port = 5_432
database_name = "test"

[jwt]
secret= "thisismysecret"
expired = 6
